### ISSUE TITLE
the footprint of Clone_Mega2560_Pro_Socket is wrong 

### ISSUE THREAD

**Issue by mmmx2000** [Alarm-Siren/arduino-kicad-library#104]
the footprint available for Clone_Mega2560_Pro_Socket is the wrong size, as can in the picture 
![Screenshot 2024-09-17 115648](https://github.com/user-attachments/assets/d7b88790-471c-4b0e-99de-53b2b9d82717)

**Comment by Alarm-Siren** [comment]
Hi @mmmx2000

I'm sorry but I do not follow what the issue is. The footprint should be correct for the non-official Meag2560 Pro. Can you be more specific about how it is wrong? 

To be clear, if you're looking for the official Arduino Mega2560, there is a different component in the library for that. The Arduino Mega2560 and Clone Mega2560 Pro are different components with different footprints.

**Comment by mmmx2000** [comment]
understood 
thanks

**Comment by ScarletThe4EyedCuda** [comment]
It is the correct size. I have used it on 3 projects with no issue.

Sent from Proton Mail Android

-------- Original Message --------
