### ISSUE TITLE
New Board: Arduino Pro Mini

### ISSUE THREAD

**Issue by Alarm-Siren** [Alarm-Siren/arduino-kicad-library#23]

**Comment by Alarm-Siren** [comment]
Board is retired, and there seems to be three different pinouts (relating to the A6 and A7 pins) depending on which specific time period and/or manufacturer made it. Unless someone specifically asks for it, I think its just not worth the effort.

**Comment by Alarm-Siren** [comment]
Welp, someone asked for it ... so I guess I'd better find a way to make it work.

@fow0ryl I'm happy to add it if you can either get me mechanical specifications for the board - i.e. the size of the board, and relative positions of the pins within it (calipers?) - or send me one of yours and I can measure it. Looking at the picture you included in #28 , it looks to me like most of the pins are standard 0.1" pitch, so I'd only need to know the locations of one from each group, e.g. 9, 10, DTR and A6 should be sufficient.

I'm also conscious that, as previously mentioned in this issue, there are other versions of this board which have different pinouts so we'll need to see if we can track them down too.

**Comment by fow0ryl** [comment]
Ok, I have measured some of my clones.
The outline dimesions differ from piece to piece a little bit, but the pins are ok.

Hope my sketch contains all you need. All values in inches ..
![Pro_Mini_Clone-Abmessungen](https://user-images.githubusercontent.com/5961849/54285457-48359380-45a2-11e9-8c2d-91b13d47c62a.jpg)

**Comment by Alarm-Siren** [comment]
Thank you very much, I think that should be enough at least to cover your variant. I'll try to get a prototype up for the weekend which you can verify against your boards?

**Comment by Alarm-Siren** [comment]
How far are the pins from the edge of the board?

**Comment by Alarm-Siren** [comment]
I've pushed a beta version of the Pro Mini Socket symbol and footprint into the 2.0.0 branch for @fow0ryl to review.

As per my previous note on the subject, there are several different variants of the Pro Mini. For example, the one pictured on Arduino's website (https://store.arduino.cc/arduino-pro-mini) has a different pin layout to the one @fow0ryl has given me specs for: Two of the Ax pins are in different places, it appears to be missing a GND pin, and the serial programming header pins are reversed.

I think its worth trying to track down as many variants as possible, and trying to come up with a systemic way of identifying them so users can select the right one within this library.

(see commit that references this issue below)

**Comment by fow0ryl** [comment]
Hello,
first of all. Thank you very much for your assistance.
Since I get a Pro Mini with original Arduino layout. I decided to create 2 footprints by myself, based on your work.
The "clone" is mostly the version you made for me. The other one is for the orignal layout.
Feel free to integrate them into your library if you like them.

I thin your description "FTDI-Serial-Header" is not a lucky one.
The serial port has nothing to do with FTDI. It's just the TTL level serial programming port.
You can use just a MAX232 to convert to RS232-Level or a FTDI or CPxxx Chip to convert to USB on this connector. Or anything you want ... 

Henning

[Arduino_Pro_Mini_Clone_Socket.kicad_mod.zip](https://github.com/Alarm-Siren/arduino-kicad-library/files/3195015/Arduino_Pro_Mini_Clone_Socket.kicad_mod.zip)
[Arduino_Pro_Mini_Socket.kicad_mod.zip](https://github.com/Alarm-Siren/arduino-kicad-library/files/3195016/Arduino_Pro_Mini_Socket.kicad_mod.zip)

**Comment by Alarm-Siren** [comment]
Thank you, I have integrated your work into the new 2.0.0 branch.
