### ISSUE TITLE
Arduino Mega 3.3V power pin is an input instead of output

### ISSUE THREAD

**Issue by pintert3** [Alarm-Siren/arduino-kicad-library#30]
I thought the Arduino 3.3V pin serves as a 3.3V output from the on board regulator. If I make a circuit and try to get a 3.3V out, the DRC keeps popping up an error claiming that I've not connected an output to the input. I don't know if it's Kicad that could have the issue, but that's where I'm at

**Comment by pintert3** [comment]
Nevermind, I read the docs again and I understand the decisions you made. Although I'm still wondering why the 3.3V wasn't made an output, knowing how it's never used as an input

**Comment by Alarm-Siren** [comment]
Yes, you are right, there is no reason for the 3.3V pin to be a Power Input on the 5V boards, as on those boards the 3.3V is supplied from a local regulator so will always be an output.

On 3.3V-based boards, I believe the Power Input compromise my still be relevant.

**Comment by Alarm-Siren** [comment]
I have changed the 3.3V pin to Power Output for the following 5V-based boards:

- Leonardo
- Mega 2560
- Micro
- Nano
- Uno

I have decided to leave the 3.3V-based boards as they are because, on those boards, you can power the microcontroller directly on the 3.3V pin, bypassing the on-board regulator. If you wanted to use this configuration, then having the pin be a Power Output would create ERC errors.
